# Generated by Django 5.0.4 on 2024-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=100)),
                ('fecha', models.CharField(max_length=10)),
            ],
        ),
    ]
