# Generated by Django 5.0.6 on 2024-06-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
